image: docker:latest

before_script:
  - apk add --no-cache rsync sshpass curl


stages:
  - deploy
  - notify

dev:
  stage: deploy
  environment:
    name: Developer
  script:
    - sshpass -p $SSH_PASS_DEV rsync -riz --links -e "ssh -o StrictHostKeyChecking=no" $SSH_DIRECTORY_LOCAL_DEV $SSH_USER_DEV@$SSH_HOST_DEV:$SSH_DIRECTORY_REMOTE_DEV
    - sh .ci-notify.sh ✅
  only:
    - dev

prod:
  stage: deploy
  environment:
    name: Production
  script:
    - sshpass -p $SSH_PASS_PROD rsync -riz --links -e "ssh -o StrictHostKeyChecking=no" $SSH_DIRECTORY_LOCAL_PROD $SSH_USER_PROD@$SSH_HOST_PROD:$SSH_DIRECTORY_REMOTE_PROD
    - sh .ci-notify.sh ✅
  only:
    - main

notify_error:
  stage: notify
  script:
    - sh .ci-error-notify.sh ❌
  when: on_failure


